config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index'

  get 'about' => 'pages#about'

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end

    private def comment_params
        params.require(:comment).permit(:username,:body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @title = "imzoughene"
        @content = "This is the content page"

    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end

    def new
        

    end

    def show
        @post = Post.find(params[:id])
    end

    def create
        #render plain: params[:post].inspect
        @post = Post.new(post_params)

        @post.save

        redirect_to @post
    end

    private def post_params
        params.require(:post).permit(:title,:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<div class="row">
    <div class="col-sm-12 py-4">
<% if(@post.comments.length) %>
<h3>Comments</h3>
<% end %>
<ul>
<% @post.comments.each do |elem| %>
    <li>
    <strong> <%= elem.username %></strong> : <%= elem.body %>
    
    <%= link_to "[X]", [elem.post,elem],
    method: :delete, 
    data:{confirm: 'Are you sure ?'} %>
    </li>
<% end %>
</ul>
</div>
</div>

app/views/comments/_form.html.erb
<div class="row">
    <div class="col-sm-12 py-4">
        <h1>Add Comment</h1>
    </div>
</div>
<%= form_for ([@post,@post.comments.build])   do |f| %>
    <% if (@post.errors.any?) %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <p>
        <%= f.label :username %><br>
        <%= f.text_field(:username, {:class=>'form-control'}) %><br>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body,{:class=>'form-control'}) %><br>
    </p>
    <p>
        <%= f.submit({:class=>'btn btn-primary'}) %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Simple Blogger</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home",posts_path %>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Create Post",new_post_path %>
      </li>
    </ul>
  </div>
</nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>about</h1>
<h2><%= @title %></h2>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<div class="row">
    <div class="col-sm-12 py-4">
        <h1>Edit Post</h1>
    </div>
</div>
<%= form_for :post,url: post_path(@post), method: :patch  do |f| %>
    <% if (@post.errors.any?) %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class=>'form-control'}) %><br>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body,{:class=>'form-control'}) %><br>
    </p>
    <p>
        <%= f.submit({:class=>'btn btn-primary'}) %>
    </p>
<% end %>

app/views/posts/index.html.erb
<h1>Blog posts</h1>
<table class='table'>
    <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Body</th>
    </tr>
    <% @posts.each do |elem| %>
    <tr>
        <th><%= elem.id %></th>
        <th><%= elem.title %></th>
        <th><%= elem.body %></th>
    </tr>
    <% end %>
</table>

app/views/posts/new.html.erb
<h1>Add Post</h1>
<%= form_for :post,url: posts_path   do |f| %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %><br>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area :body %><br>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h2><%= @post.id %></h1>
<h3><%= @post.body %></h1>